apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fixit
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fixit
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fixit
    spec:
      containers:
      - name: fixit
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
